default: &default
  model: "user"
  model_uniq_identifier: "email"
  create_record_on_the_fly: "true"
  sso_session_timeout: "60"
  identity_provider_secret_key: 'my$ecretK3y'
  sso_server: "true"

development:
  <<: *default
  identity_provider_secret_key: 'my$ecretK3y'
  sso_session_timeout: <%= ENV["SSO_SESSION_TIMEOUT"] %>

test:
  <<: *default
  identity_provider_secret_key: 'my$ecretK3y'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  # identity_provider_secret_key: <%= ENV["SSO_SECRET_KEY"] %>
  sso_session_timeout: <%= ENV["SSO_SESSION_TIMEOUT"] %>
